# Generated by Django 3.1.3 on 2021-01-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
